title: Hypha Worker Co-operative
email: hello@hypha.coop
phone: +1 437-887-6936
linkedin: https://www.linkedin.com/company/hyphacoop/
twitter: https://twitter.com/hyphacoop/
# instagram: https://instagram.com/hyphacoop/
# facebook: https://www.facebook.com/hyphacoop/
